# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Concise and Not
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
This site has posts that contain a concise explanation of a technology or concept. It then goes into expansive detail. The concise section is great as a refrence and the descriptive are is meant for deep learning.
url: "http://ericjaystevens.github.io
twitter_username: ericjaystevens
github_username:  ericjaystevens

# Build settings
markdown: kramdown
